"""
Module: reports.py
Description: Compiles analytics matrices into localized UI layouts or system files.
Author: Senior Cybersecurity Engineer
"""
import os
import logging

class ReportEngine:
    @staticmethod
    def print_terminal_report(analysis_results: dict):
        """Displays data in standard console structures."""
        print("\n" + "="*60)
        print("          PASSWORD SECURITY ASSESSMENT REPORT")
        print("="*60)
        print(f" Metrics & Analysis  :")
        print(f"  [-] Character Length : {analysis_results['password_length']}")
        print(f"  [-] Shannon Entropy  : {analysis_results['entropy_bits']} bits")
        print(f"  [-] Strength Category: {analysis_results['strength_tier'].upper()}")
        print(f"  [-] Risk Designation : {analysis_results['risk_rating'].upper()}")
        print("-" * 60)
        
        print(" Defensive Diagnostics & Vulnerabilities:")
        if not analysis_results['findings']:
            print("  [+] No flaws or weak design parameters detected.")
        else:
            for finding in analysis_results['findings']:
                print(f"  [!] {finding}")
        
        print("-" * 60)
        print(" Security Remediation Protocols:")
        if not analysis_results['recommendations']:
            print("  [+] Current construction adheres to standard best practices.")
        else:
            for rec in analysis_results['recommendations']:
                print(f"  [*] {rec}")
        print("="*60 + "\n")

    @staticmethod
    def export_to_markdown(analysis_results: dict, filename: str = "password_audit_report.md"):
        """Exports the collected telemetry to a production-grade markdown compliance artifact."""
        try:
            md_content = f"""# Cybersecurity Password Audit Assessment Report
**Generated by Secure Password Creation Guide Framework**

## 1. Executive Summary Telemetry
| Metric | Assessment Target Value |
| :--- | :--- |
| **Password Character Length** | {analysis_results['password_length']} |
| **Computed Shannon Entropy** | {analysis_results['entropy_bits']} Bits |
| **Calculated Security Tier** | `{analysis_results['strength_tier']}` |
| **Operational Risk Index** | **{analysis_results['risk_rating'].upper()}** |

## 2. Technical Findings Log
"""
            if not analysis_results['findings']:
                md_content += "- `PASS`: No automated exploitation structural vectors identified.\n"
            else:
                for finding in analysis_results['findings']:
                    md_content += f"- **VULN**: {finding}\n"

            md_content += "\n## 3. Prescriptive Security Recommendations\n"
            if not analysis_results['recommendations']:
                md_content += "- `COMPLIANT`: Configuration matches optimal complexity frameworks.\n"
            else:
                for rec in analysis_results['recommendations']:
                    md_content += f"- [ ] {rec}\n"

            with open(filename, "w") as f:
                f.write(md_content)
            print(f"[+] Operational Report safely structured and written out to: {os.path.abspath(filename)}")
        except IOError as e:
            logging.error(f"Failed writing export report payload data: {str(e)}")